version: 1.0.{build}
image: Previous Visual Studio 2017
init:
- cmd: >-
    nuget sources add -name DiscordNet -Source https://www.myget.org/F/discord-net/api/v3/index.json


    dotnet restore
build:
  verbosity: minimal
test: off